cc_test(
    name = "convex_hull_test",
    size = "small",
    srcs = [
        "convex_hull_test.cpp",
    ],
    deps = [
        "//src:geometry",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "intersection_test",
    size = "small",
    srcs = [
        "intersection_test.cpp",
    ],
    deps = [
        "//src:geometry",
        "@gtest//:gtest_main",
    ],
)
