cc_binary(
    name = "triangle_square_intersection_1",
    srcs = ["triangle_square_intersection_1.cpp"],
    deps = [
        "//src:geometry",
        "@simple_svg",
    ],
)

cc_binary(
    name = "triangle_square_intersection_2",
    srcs = ["triangle_square_intersection_2.cpp"],
    deps = [
        "//src:geometry",
        "@simple_svg",
    ],
)

cc_binary(
    name = "triangle_square_intersection_3",
    srcs = ["triangle_square_intersection_3.cpp"],
    deps = [
        "//src:geometry",
        "@simple_svg",
    ],
)
