cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cc"],
    deps = [
        "@benchmark",
        "@gtest",
        "@simple_svg",
    ],
)

#cc_library(
#    name = "clip_polygon",
#    srcs = ["clip_polygon.cpp"],
#)
